version: '2'

services:
  eureka:
      image: devoxx-talk-2016/eureka-server
      environment:
        - EUREKA_HOSTNAME=eureka-server
      ports:
        - "8761"
  config-server:
    image: devoxx-talk-2016/config-server
    environment:
      - EUREKA_HOSTNAME=eureka
    ports:
      - "8888"
    depends_on:
      - eureka
  zuul-proxy:
    image: devoxx-talk-2016/zuul-proxy
    environment:
      - EUREKA_HOSTNAME=eureka
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - config-server
  service-one:
    image: devoxx-talk-2016/service-one
    environment:
     - EUREKA_HOSTNAME=eureka
    ports:
      - "8082"
    depends_on:
      - eureka
      - config-server
  service-two:
      image: devoxx-talk-2016/service-two
      environment:
       - EUREKA_HOSTNAME=eureka
      ports:
        - "8082"
      depends_on:
        - eureka
        - config-server
